version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"  # Para DBeaver
    environment:
      MYSQL_ROOT_PASSWORD: root25
      MYSQL_DATABASE: funkopop_collections
      MYSQL_PASSWORD: root25
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d  # Auto-importa .sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
